Add Lambda UDF demonstrating Glue Schema Registry integration for Avro data
aws-samples/amazon-redshift-udfs pull request #48
Opened 2023-08-25 20:11 UTC by mmehrten

*Issue #, if available:* N/A

*Description of changes:* 

    Add Lambda UDF to demonstrate decoding Avro data in Redshift using the Glue Schema Registry

    Add logic for installing Lambda layers for Python Lambda UDFs

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-25 20:53 UTC, rjvgupta requested changes
Please review and resolve comments.

2023-08-25 20:53 UTC, rjvgupta commented on bin/deployFunction.sh
Can you make this iterative?  i.e. move your code inside the while loop?

2023-08-25 20:53 UTC, rjvgupta commented on README.md
Can you also update the lambda.yaml description and include a note; if you're using the requirements.txt to drive the creation of layers there needs to be a separate resource for each dependency and those layers need to be referenced in the main lambda function resource. You can even reference your function as an example.

2023-08-25 20:53 UTC, rjvgupta commented on lambda-udfs/f_glue_schema_registry_avro_to_json(varchar,varchar)/function.sql
Can you add a little more to the description with references to documentation?  E.g. Answering how could Avro data ever get inside Redshift like this?  Would it be in a varbyte field and do you need to cast it to get to that string representation?  Also, since the return is string but you mention SUPER, how would one cast the results to make it more usable?  Lastly, you should describe each function parameter.  For the SchemaRegistry and the Schema also mention the IAM policy will give this function access to any/all registries and all schemas and that if they want to lock the access down, they can modify the policy after deployment.

2023-08-25 20:53 UTC, rjvgupta commented on lambda-udfs/f_glue_schema_registry_avro_to_json(varchar,varchar)/lambda.yaml
This resource "AvroLambdaUDF" is specific to your example and not applicable to any customer deploying this.  Can you change to "*" and pass a parameter into your function instead?

2023-08-28 16:01 UTC, mmehrten commented on lambda-udfs/f_glue_schema_registry_avro_to_json(varchar,varchar)/function.sql
Yes, a link to the blog post associated with this example will be added once it is published

2023-08-28 18:29 UTC, rjvgupta requested changes
Almost there.  Just a request on the parameters.

2023-08-28 18:29 UTC, rjvgupta commented on README.md
made some adjustments, see comments in other files for some context as to why.

2023-08-28 18:29 UTC, rjvgupta commented on lambda-udfs/f_glue_schema_registry_avro_to_json(varchar,varchar)/lambda.yaml
> +          GLUE_REGISTRY_NAME: AvroLambdaUDF
Instead of hard-coding this, you should add as a parameter e.g. f-glue-schema-registry-avro-to-json-varchar-varchar-varchar

2023-08-28 18:29 UTC, rjvgupta commented on lambda-udfs/f_glue_schema_registry_avro_to_json(varchar,varchar)/lambda.yaml
> +          REGISTRY_NAME = os.environ["GLUE_REGISTRY_NAME"]
Instead of an env variable, this should be a function parameter.

2023-08-28 18:29 UTC, rjvgupta commented on lambda-udfs/f_glue_schema_registry_avro_to_json(varchar,varchar)/input.csv
add "AvroLambdaUDF" as a parameter so you don't have to hard-code in the lambda function.

2023-08-28 19:44 UTC, rjvgupta approved these changes
Good to go.

2023-08-28 19:44 UTC, merged